In [1]:
import sympy as sym
import numpy as np
import dill

print(np.__version__)

2.5.1


In [2]:
sym.init_printing(use_unicode=True)

In [66]:
p_IMU_global = np.array([0, -9, 0, 0])
p_face_global = np.array([0, -9, 5, 0])
# p_face_cam = np.array([0, 0, 0, 5])

q_IMU_global = np.array([np.cos(np.deg2rad(6)), np.sin(np.deg2rad(6)), 0, 0])

scene_IMU_translation = np.array([0, 0, -0.0013, -0.00662])
scene_IMU_rotation = np.array([np.cos(np.deg2rad(-51)), np.sin(np.deg2rad(-51)), 0, 0])

q_IMU_global

array([0.9945219 , 0.10452846, 0.        , 0.        ])

## helpers

In [67]:
def left_quat_matrix(q):
    qw, qx, qy, qz = q[0], q[1], q[2], q[3]
    
                            #w
                            #x
                            #y
                            #z
    return np.array([
        [qw, -qx, -qy, -qz], 
        [qx,  qw, -qz,  qy], 
        [qy,  qz,  qw, -qx], 
        [qz, -qy,  qx,  qw]  
    ])

def quat_inv(q):
    return np.array([q[0], -q[1], -q[2], -q[3]])

# from global to IMU

In [68]:
translated = p_face_global - p_IMU_global
first_rotation = left_quat_matrix(quat_inv(q_IMU_global)) @ translated
second_rotation = left_quat_matrix(first_rotation) @ q_IMU_global

p_face_IMU = second_rotation

p_face_IMU


array([ 0.        ,  0.        ,  4.890738  , -1.03955845])

# from global to face

In [69]:
translated2 = p_face_IMU - scene_IMU_translation
first_rotation2 = left_quat_matrix(quat_inv(scene_IMU_rotation)) @ translated2
second_rotation2 = left_quat_matrix(first_rotation2) @ scene_IMU_rotation

p_face_cam = second_rotation2

p_face_cam

array([ 0.        ,  0.        , -0.00674562,  4.99989522])